name: gps_tracker
description: GPS Clock-In Tracker mobile application for employee shift tracking with location verification.
publish_to: 'none'
version: 1.0.0+77

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.0
  connectivity_plus: ^6.0.0
  device_info_plus: ^11.0.0
  csv: ^6.0.0
  fl_chart: ^1.1.1
  mobile_scanner: ^7.1.4
  cupertino_icons: ^1.0.6
  disable_battery_optimization: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_activity_recognition: ^4.0.0
  flutter_foreground_task: ^9.0.0
  flutter_local_notifications: ^18.0.0
  flutter_map: ^6.0.0
  flutter_riverpod: ^2.5.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  http: ^1.2.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.10.0
  printing: ^5.12.0
  share_plus: ^7.2.0
  sqflite_sqlcipher: ^3.1.0+1
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.0
  uuid: ^4.0.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
